import Navbar from "@/components/Navbar";
import "./globals.css";
import {
  alexandria,
  playfair_display,
  brygada_1918,
  noto_serif_devanagari,
} from "@/lib/fonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${alexandria.variable} ${playfair_display.variable} ${brygada_1918.variable} ${noto_serif_devanagari.variable}`}
      >
        <Navbar />

        {children}
      </body>
    </html>
  );
}
